linters:
  disable-all: true
  enable:
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - gosec
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam
    - unused
    - govet
    - gosec

issues:
  exclude:
    - G404
    - G114
  exclude-files:
    - ".*_test.go"
