kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: do-agent
  namespace: monitoring
---
# DaemonSet to create a do-agent on each node that scrapes node metrics
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: do-node-agent
  name: do-node-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: do-node-agent
  template:
    metadata:
      labels:
        app: do-node-agent
    spec:
      containers:
      - name: do-node-agent
        image: docker.io/digitalocean/do-agent:unstable
        resources:
          limits:
            cpu: 102m
            memory: 100Mi
          requests:
            cpu: 102m
            memory: 80Mi
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
        - mountPath: /host/root
          mountPropagation: HostToContainer
          name: root
          readOnly: true
        command:
          - "/bin/do-agent"
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: do-agent
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
---
# Deployment to create a single do-agent that scrape kube-state metrics
apiVersion: apps/v1beta2
kind: Deployment 
metadata:
  labels:
    app: do-kube-agent
  name: do-kube-agent
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-kube-agent
  template:
    metadata:
      labels:
        app: do-kube-agent
    spec:
      containers:
      - name: do-kube-agent
        image: docker.io/digitalocean/do-agent:unstable
        resources:
          limits:
            cpu: 102m
            memory: 100Mi
          requests:
            cpu: 102m
            memory: 80Mi
        command:
          - "/bin/do-agent"
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
          - "--k8s-metrics-path=http://kube-state-metrics.kube-system.svc.cluster.local:8080/metrics"
          - "--no-collector.node"
          - "--no-collector.processes"
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: do-agent
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
